[package]
name = "zkapi-tree-prover"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[dependencies]
ark-bn254.workspace = true
ark-ff.workspace = true
ark-ec.workspace = true
ark-groth16.workspace = true
ark-serialize.workspace = true
ark-crypto-primitives = { version = "=0.5.0", features = ["sponge", "r1cs"] }
ark-relations = "=0.5.1"
ark-r1cs-std = "=0.5.0"
rand = "=0.8.5"
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
ed25519-dalek = "=2.2.0"
serde_jcs = "=0.1.0"
zkapi-layout2 = { path = "../zkapi-layout2" }
zkapi-poseidon = { path = "../zkapi-poseidon" }
zkapi-solana-crypto = { path = "../zkapi-solana-crypto" }
zkapi-solana-types.workspace = true
[dev-dependencies]
ark-ed-on-bn254.workspace = true
zkapi-core.workspace = true
zkapi-proof.workspace = true
zkapi-types.workspace = true
bs58 = "=0.5.1"
