//! Deterministic export from pinned upstream VKs and unchanged Poseidon parameters.
use ark_bn254::{Bn254, Fr};
use ark_crypto_primitives::sponge::poseidon::find_poseidon_ark_and_mds;
use ark_ff::PrimeField;
use ark_groth16::VerifyingKey;
use ark_serialize::CanonicalDeserialize;
use std::{fmt::Write, fs, path::Path};
use zkapi_solana_crypto::SolanaVerifyingKey;
fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let mut out = String::from("// Generated by cargo run -p zkapi-solana-crypto --example export_sbf.\n// Upstream test setup; NOT a production ceremony.\nuse groth16_solana::groth16::Groth16Verifyingkey;\n");
    for name in ["request", "withdrawal"] {
        let raw = fs::read(root.join(format!("vendor/ethereum-zkapi/protocol/setup/v2/{name}.vk")))
            .unwrap();
        let mut bytes = raw.strip_prefix(b"zkapi-v2-note-bound-v1\0").unwrap();
        let vk = VerifyingKey::<Bn254>::deserialize_compressed(&mut bytes).unwrap();
        assert!(bytes.is_empty());
        let converted = SolanaVerifyingKey::from_arkworks(&vk).unwrap();
        let k = converted.as_verifying_key();
        writeln!(out, "pub static {}: Groth16Verifyingkey<'static> = Groth16Verifyingkey {{ nr_pubinputs: {}, vk_alpha_g1: {:?}, vk_beta_g2: {:?}, vk_gamme_g2: {:?}, vk_delta_g2: {:?}, vk_ic: &{:?} }};", name.to_uppercase(), k.nr_pubinputs,k.vk_alpha_g1,k.vk_beta_g2,k.vk_gamme_g2,k.vk_delta_g2,k.vk_ic).unwrap();
    }
    fs::write(root.join("programs/i02-harness/src/vk.rs"), out).unwrap();
    let (ark, mds) = find_poseidon_ark_and_mds::<Fr>(Fr::MODULUS_BIT_SIZE as u64, 2, 8, 57, 0);
    let mut out = String::from("// Generated from upstream Arkworks 0.5 Poseidon parameters.\nuse ark_bn254::Fr;\nuse ark_ff::MontFp;\n");
    for (name, rows) in [("ARK", ark), ("MDS", mds)] {
        writeln!(out, "pub const {name}: [[Fr; 3]; {}] = [", rows.len()).unwrap();
        for row in rows {
            out.push('[');
            for f in row {
                write!(out, "MontFp!(\"{f}\"),").unwrap();
            }
            out.push_str("],\n");
        }
        out.push_str("];\n");
    }
    fs::write(root.join("crates/zkapi-poseidon/src/constants.rs"), out).unwrap();
}
