/** Explicit native/OpenClaw devnet acceptance adapter. Production runtime and
 * Go frontend; the Unix egress uses the existing bounded devnet operator host.
 * This harness does not replace the SDK financial state machine. Never point it
 * at an unrelated journal. Fresh unfunded initialization sends no AUTH, inference
 * or chain transaction; later starts/shutdown use the existing SDK recovery. */
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,lstat,rename,open,chmod,mkdtemp} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {createKeyPairSignerFromBytes} from '@solana/kit';
import {decodeTransaction,transactionSignature} from '@zkapi/solana-sdk/solana';
import bs58 from 'bs58';
import {loadDeploymentAssets} from '@zkapi/solana-sdk/deployment';
import {parseStrictJson,jcsBytes} from '@zkapi/solana-sdk/trust';
import {writeNodeResponse} from '@zkapi/solana-sdk/clientd-network';
import {unlockJournalKey} from '@zkapi/solana-sdk/secret-custody';
import {importJournalKey,EncryptedJournal} from '@zkapi/solana-sdk/journal';
import {NativeJournalStore} from '@zkapi/solana-sdk/journal-node';
import {validateNoteJournal} from '@zkapi/solana-sdk/control';
import {externalRelay} from './external_sdk_live.mjs';
const hash=value=>createHash('sha256').update(value).digest('hex');
async function privateRead(path,max=1024*1024){const info=await lstat(path);assert.ok(info.isFile()&&!info.isSymbolicLink()&&(info.mode&0o077)===0&&info.size<=max);return readFile(path);}
async function save(path,value,exclusive=false){const temporary=exclusive?path:path+'.'+randomUUID()+'.tmp';const file=await open(temporary,'wx',0o600);try{await file.writeFile(JSON.stringify(value,null,2)+'\n');await file.sync();}finally{await file.close();}if(!exclusive)await rename(temporary,path);const directory=await open(resolve(path,'..'),'r');try{await directory.sync();}finally{await directory.close();}}
async function execute(command,args,input=''){const child=spawn(command,args,{stdio:['pipe','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',v=>stdout+=v);child.stderr.on('data',v=>stderr+=v);child.stdin.end(input);const[code]=await once(child,'exit');assert.equal(code,0,stderr);return stdout;}
const [command,configPath,...rest]=process.argv.slice(2);assert.ok(['init','serve','action','inspect','command'].includes(command));assert.ok(configPath);
if(command==='init'){
 const [sourcePath,installPath]=rest;assert.ok(sourcePath&&installPath);const directory=resolve(configPath,'..');await mkdir(directory,{mode:0o700});
 const source=parseStrictJson(await privateRead(sourcePath));const profileBytes=await readFile(source.profile);assert.equal(hash(profileBytes),source.profileSha256);const profile=parseStrictJson(profileBytes);assert.equal(profile.chain,'solana:devnet');assert.equal(profile.mode,'direct_openrouter');
 const assets=await loadDeploymentAssets('https://bundle.zkapi.invalid/bundle.json',{bundleSha256:source.bundleSha256,fetch:async(url)=>{const target=new URL(String(url));assert.equal(target.origin,'https://bundle.zkapi.invalid');assert.match(target.pathname,/^\/[a-zA-Z0-9][a-zA-Z0-9.-]*$/);return new Response(await readFile(join(source.bundleDirectory,target.pathname.slice(1))));}});assert.equal(hash(jcsBytes(assets.trust)),hash(jcsBytes(profile.trust)));
 const install=resolve(installPath),release=JSON.parse(await readFile(join(install,'release.json'),'utf8')),artifactDir=join(directory,'artifacts');await mkdir(artifactDir,{mode:0o700});
 const artifactPaths={additional:{}};for(const[name,value]of Object.entries(assets.artifacts)){if(name==='additional'){for(const[id,bytes]of Object.entries(value)){assert.match(id,/^[a-zA-Z0-9_-]+$/);const file=join(artifactDir,'extra-'+id);await writeFile(file,bytes,{mode:0o600});artifactPaths.additional[id]=file;}}else{const file=join(artifactDir,name);await writeFile(file,value,{mode:0o600});artifactPaths[name]=file;}}
 const manifestPath=join(artifactDir,'manifest.json');await writeFile(manifestPath,assets.manifest,{mode:0o600});
 const models=[];for(const[index,model]of profile.models.entries()){const tariff=join(artifactDir,`tariff-${index}.json`);await save(tariff,model.tariff,true);models.push({id:model.id,provider:model.provider,apis:model.apis,tariff});}
 const runtime={manifest:manifestPath,policy:assets.trust,artifacts:artifactPaths,mode:profile.mode,models,key_reuse_seconds:60,rpc:profile.rpcUrl,indexer:profile.indexerOrigin,direct_provider_bases:profile.directProviderBases,preparation_commitment:'confirmed'};
 const runtimePath=join(directory,'reviewed-runtime.json'),networkPath=join(directory,'reviewed-network.json');await save(runtimePath,runtime,true);await save(networkPath,{mode:'direct',routes:[{origin:profile.trust.expected.control_api_origin,prefix:'/zkapi/v1'},{origin:'https://openrouter.ai',prefix:'/api/v1'},{origin:profile.rpcUrl,prefix:'/'},{origin:profile.indexerOrigin,prefix:'/zkapi/v1/tree'}]},true);
 const profilePath=join(directory,'profile'),pin=hash(await readFile(join(install,'release.json')));const setup=JSON.parse(await execute(join(install,'bin/clientd'),['setup','--profile',profilePath,'--distribution',join(install,'release.json'),'--sha256',pin,'--runtime-config',runtimePath,'--runtime-sha256',hash(await readFile(runtimePath)),'--network-config',networkPath,'--listen','127.0.0.1:8788']));
 const secretBytes=Uint8Array.from(JSON.parse(await privateRead(source.walletFile)));let wallet;try{wallet=await createKeyPairSignerFromBytes(secretBytes);}finally{secretBytes.fill(0);}await writeFile(join(directory,'passphrase'),randomBytes(32).toString('hex'),{mode:0o600});
 const config={schema:1,profile:setup.profile,installation:install,distributionSha256:pin,publicProfile:source.profile,publicProfileSha256:source.profileSha256,hostOrigin:source.hostOrigin,walletFile:source.walletFile,passphraseFile:join(directory,'passphrase'),state:join(directory,'acceptance.json'),directory,frontend:join(directory,'frontend'),maxInference:3,maxAuthorizations:2,depositMicroUsdc:'2000000',model:models[0].id};
 await save(configPath,config,true);await save(config.state,{schema:1,auth:[],inferences:[],transactions:[],action:null,blocked:false},true);
 const roles=Object.fromEntries(['payer','feePayer','uploader','rentPayer','tokenOwner'].map(role=>[role,wallet.address]));await save(join(directory,'deposit.json'),{action:'deposit',amount:config.depositMicroUsdc,roles},true);await save(join(directory,'withdraw.json'),{action:'withdraw',mode:'mutual_close',destination_owner:wallet.address,roles},true);
 const openclaw=JSON.parse(await execute(join(install,'bin/clientd'),['openclaw-config',setup.profile,'--model',models[0].id,'--context-window','32000','--max-tokens','128']));const workspace=join(directory,'work');await mkdir(workspace,{mode:0o700});await writeFile(join(workspace,'probe.txt'),'ZKAPI_NATIVE_TOOL_OK\n',{mode:0o600});openclaw.agents.defaults.workspace=workspace;openclaw.agents.defaults.skipBootstrap=true;openclaw.agents.defaults.thinkingDefault='off';openclaw.tools={allow:['read']};openclaw.plugins={enabled:false};await save(join(directory,'openclaw.json'),openclaw,true);
 await execute(resolve('target/toolchains/go/bin/go'),['-C','apps/clientd','build','-o',config.frontend,'./testdata/openclaw-frontend.go']);
 console.log(JSON.stringify({prepared:true,profile:setup.profile,model:config.model,publicDevnetFunding:false,inferenceSends:0,distributionSha256:pin}));
}else{
 const config=parseStrictJson(await privateRead(configPath));assert.equal(config.schema,1);assert.equal(config.maxInference,3);assert.equal(config.maxAuthorizations,2);assert.equal(config.depositMicroUsdc,'2000000');const profile=parseStrictJson(await readFile(config.publicProfile));assert.equal(hash(await readFile(config.publicProfile)),config.publicProfileSha256);
 const state=parseStrictJson(await privateRead(config.state));const runtime=parseStrictJson(await privateRead(join(config.profile,'runtime.json')));const cli=join(config.installation,'bin/clientd');
 if(command==='action'){
  assert.ok(['text','tools'].includes(rest[0]));assert.equal(state.blocked,false);assert.ok(!state.actions?.[rest[0]]);state.actions??={};state.actions[rest[0]]={startedAt:new Date().toISOString(),inferenceStart:state.inferences.length};state.action=rest[0];await save(config.state,state);console.log(JSON.stringify({action:state.action,maximumRemaining:config.maxInference-state.inferences.length}));
 }else if(command==='command'){
  assert.ok(['deposit','withdraw','advance','prove','status','recover','close','clear-unaccepted-auth','recover-expired-setup','retry-rejected'].includes(rest[0]));let args=['request',config.profile],input='';if(['deposit','withdraw'].includes(rest[0])){args.push('wallet');input=await readFile(join(config.directory,rest[0]+'.json'),'utf8');}else if(['status','recover','close'].includes(rest[0]))args.push(rest[0]);else{args.push('wallet');input=JSON.stringify({action:rest[0]});}console.log(await execute(cli,args,input));
 }else if(command==='inspect'){
  const passphrase=await privateRead(config.passphraseFile,4096);const raw=await unlockJournalKey(runtime.custody,passphrase);passphrase.fill(0);const key=await importJournalKey(raw);raw.fill(0);const manifest=JSON.parse(await readFile(runtime.manifest,'utf8'));const store=await NativeJournalStore.open(runtime.journal);const journal=new EncryptedJournal(store,key,{deploymentId:manifest.deployment_id,pool:manifest.pool},validateNoteJournal);const record=await journal.read(runtime.note_id);const value=record?.value;
  const summary={scope:'native runtime and production Go frontend with bounded operator devnet egress',mode:runtime.mode,noteId:runtime.note_id,balanceMicroUsdc:value?.state.balance_micro_usdc??'0',wallet:value?.wallet?.status??'unfunded',walletOperation:value?.wallet?.operation?{kind:value.wallet.operation.kind,phase:value.wallet.operation.phase,signature:value.wallet.operation.tx?.signature??null}:null,pending:value?.pending?{phase:value.pending.phase,operations:value.pending.operations.map(o=>({id:o.id,phase:o.phase}))}:null,history:value?.history.map(h=>({chargeMicroUsdc:h.settlement.charge_micro_usdc,operations:h.operations.map(o=>({id:o.id,phase:o.phase}))}))??[],walletHistory:value?.wallet?.history.map(o=>({kind:o.kind,phase:o.phase}))??[],authCount:state.auth.length,inferenceCount:state.inferences.length,blocked:state.blocked,transactions:state.transactions,providerResponses:state.inferences.map(i=>({operationId:i.operationId,status:i.status,completed:i.completed,responseSha256:i.responseSha256})),journalHead:record?.head??null};await save(join(config.directory,'inspection.json'),summary);console.log(JSON.stringify(summary,null,2));
 }else{
  assert.equal(hash(await readFile(join(config.installation,'release.json'))),config.distributionSha256);await writeFile(join(config.directory,'runner.pid'),String(process.pid)+'\n',{mode:0o600});const release=JSON.parse(await readFile(join(config.installation,'release.json'),'utf8'));for(const[file,want]of Object.entries(release.files)){const full=join(config.installation,file),info=await lstat(full);assert.ok(info.isFile()&&!info.isSymbolicLink()&&(info.mode&0o022)===0);assert.equal(hash(await readFile(full)),want);}
  const sockets=await mkdtemp(join(tmpdir(),'zkapi-native-'));await chmod(sockets,0o700);const sdkSocket=join(sockets,'sdk.sock'),relaySocket=join(sockets,'relay.sock');let serial=Promise.resolve();const mutate=fn=>{const promise=serial.then(async()=>{const saved=parseStrictJson(await privateRead(config.state));const result=await fn(saved);await save(config.state,saved);return result;});serial=promise.catch(()=>{});return promise;};
  let nativeJournal;
  const relay=externalRelay(profile,config.hostOrigin,async event=>{if(!['auth','inference'].includes(event.kind)&&!(event.kind==='rpc'&&event.rpc.method==='sendTransaction'))return;await mutate(async saved=>{
   if(event.kind==='auth'){const body=parseStrictJson(Buffer.from(event.body));const id=body.authorization.request_id,bodyHash=hash(Buffer.from(event.body));const prior=saved.auth.find(x=>x.id===id);if(prior)assert.equal(prior.bodySha256,bodyHash);else{assert.equal(saved.blocked,false);assert.ok(['text','tools'].includes(saved.action));assert.ok(saved.auth.length<config.maxAuthorizations);saved.auth.push({id,bodySha256:bodyHash,action:saved.action});}}
   if(event.kind==='inference'){assert.equal(saved.blocked,false);assert.ok(saved.inferences.length<config.maxInference);assert.ok(['text','tools'].includes(saved.action));assert.ok(saved.inferences.filter(i=>i.action===saved.action).length<(saved.action==='text'?1:2));const pending=(await nativeJournal.read(runtime.note_id)).value.pending,operation=pending.operations.at(-1);assert.equal(operation.phase,'send_unknown');if(operation.bodyRedacted===true){assert.equal(operation.bodyBase64,'');assert.equal(operation.bodySha256,hash(Buffer.from(event.body)));}else assert.equal(hash(Buffer.from(operation.bodyBase64,'base64')),hash(Buffer.from(event.body)));assert.ok(!saved.inferences.some(i=>i.operationId===operation.id));saved.inferences.push({operationId:operation.id,authorizationId:pending.prepared.request.authorization.request_id,action:saved.action,bodySha256:hash(Buffer.from(event.body)),startedAt:new Date().toISOString(),completed:false});saved.blocked=true;}
   if(event.kind==='rpc'&&event.rpc.method==='sendTransaction'){const bytes=Buffer.from(event.rpc.params[0],'base64'),tx=decodeTransaction(bytes),signature=transactionSignature(tx);assert.ok(!saved.transactions.some(x=>x.signature===signature),'exact-signature resend refused');saved.transactions.push({signature,bytes:bytes.length,sha256:hash(bytes),sendRecordedAt:new Date().toISOString()});}
  });});
  const relayServer=createServer(async(req,res)=>{const abort=new AbortController();res.on('close',()=>{if(!res.writableEnded)abort.abort()});try{assert.equal(req.url,'/fetch');const target=String(req.headers['x-zkapi-target']);const chunks=[];let length=0;for await(const chunk of req){length+=chunk.length;assert.ok(length<=4*1024*1024);chunks.push(chunk);}const headers=new Headers();for(const name of ['authorization','content-type','accept','idempotency-key','anthropic-version'])if(req.headers[name])headers.set(name,String(req.headers[name]));const provider=target==='https://openrouter.ai/api/v1/chat/completions';const result=await relay(target,{method:req.method,headers,body:req.method==='GET'?undefined:Buffer.concat(chunks).toString('utf8'),signal:abort.signal});if(!provider){await writeNodeResponse(result,res);return;}
   const savedChunks=[];let bytes=0,completion;const complete=()=>completion??=(async()=>{const response=Buffer.concat(savedChunks),text=new TextDecoder('utf-8',{fatal:true}).decode(response);const terminal=result.headers.get('content-type')?.includes('text/event-stream')?text.trimEnd().endsWith('data: [DONE]'):typeof JSON.parse(text).choices?.[0]?.finish_reason==='string';const current=parseStrictJson(await privateRead(config.state)).inferences.at(-1),responseFile=join(config.directory,`provider-response-${current.operationId}.txt`);const evidence=await open(responseFile,'wx',0o600);try{await evidence.writeFile(response);await evidence.sync();}finally{await evidence.close();}const evidenceDirectory=await open(config.directory,'r');try{await evidenceDirectory.sync();}finally{await evidenceDirectory.close();}await mutate(saved=>{const last=saved.inferences.at(-1);assert.equal(last.operationId,current.operationId);last.status=result.status;last.completed=terminal;last.responseSha256=hash(response);last.responseFile=responseFile;saved.blocked=!terminal||result.status<200||result.status>=300;});})();const reader=result.body?.getReader();const body=reader?new ReadableStream({async pull(controller){try{const next=await reader.read();if(next.done){await complete();controller.close();}else{bytes+=next.value.length;assert.ok(bytes<=2*1024*1024);savedChunks.push(Buffer.from(next.value));controller.enqueue(next.value);}}catch(error){await reader.cancel();controller.error(error);}},async cancel(){await reader.cancel();await complete();}}):null;await writeNodeResponse(new Response(body,{status:result.status,headers:result.headers}),res);
  }catch{if(!res.headersSent){res.writeHead(503,{'Content-Type':'application/json'});res.end('{"error":"bounded acceptance relay rejected; inspect saved state"}');}else res.destroy();}});await new Promise(r=>relayServer.listen(relaySocket,r));await chmod(relaySocket,0o600);
  const wallet=JSON.parse(await privateRead(config.walletFile)),passphrase=(await privateRead(config.passphraseFile,4096)).toString();let initialize=false;try{await lstat(runtime.custody);}catch(error){assert.equal(error.code,'ENOENT');initialize=true;}
  const child=spawn(join(config.installation,'bin/node'),[join(config.installation,'apps/clientd/runtime.ts'),join(config.profile,'runtime.json'),sdkSocket,relaySocket],{env:{PATH:join(config.installation,'bin'),RAYON_NUM_THREADS:'4'},stdio:['pipe','pipe','pipe']});child.stderr.on('data',()=>{});child.stdin.write(JSON.stringify({passphrase,wallet_seed_base64:Buffer.from(wallet.slice(0,32)).toString('base64'),initialize_key:initialize})+'\n');let startupTimer;const ready=await Promise.race([once(child.stdout,'data').then(([b])=>String(b)),once(child,'exit').then(([code])=>{throw Error('native runtime exited '+code)}),new Promise((_,reject)=>{startupTimer=setTimeout(()=>reject(Error('native startup timeout')),120000);})]);clearTimeout(startupTimer);assert.match(ready,/READY/);const secretKey=await unlockJournalKey(runtime.custody,new TextEncoder().encode(passphrase));const importedKey=await importJournalKey(secretKey);secretKey.fill(0);const nativeManifest=JSON.parse(await readFile(runtime.manifest,'utf8'));nativeJournal=new EncryptedJournal(await NativeJournalStore.open(runtime.journal),importedKey,{deploymentId:nativeManifest.deployment_id,pool:nativeManifest.pool},validateNoteJournal);
  const inference=(await privateRead(join(config.profile,'inference-token'),128)).toString().trim(),management=(await privateRead(join(config.profile,'management-token'),128)).toString().trim();const front=spawn(config.frontend,[sdkSocket,'8788'],{stdio:['pipe','pipe','pipe']});front.stdin.end(JSON.stringify({inference_token:inference,management_token:management}));await once(front.stdout,'data');const observed=parseStrictJson(await privateRead(config.state));console.log(JSON.stringify({ready:true,listen:'127.0.0.1:8788',custodyInitialized:initialize,publicDevnet:true,transactionCount:observed.transactions.length,authCount:observed.auth.length,inferenceCount:observed.inferences.length}));
  await new Promise(r=>{process.once('SIGINT',r);process.once('SIGTERM',r);child.once('exit',r);});front.kill('SIGTERM');if(child.exitCode===null&&child.signalCode===null){const stopped=once(child,'exit');child.kill('SIGTERM');await stopped;}relayServer.closeAllConnections();relayServer.close();console.log(JSON.stringify({stopped:true}));
 }
}
