[workspace]
[package]
name = "zkapi-vault"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
publish = false
[lib]
crate-type = ["cdylib", "lib"]
[features]
default = ["local-test"]
local-test = []
devnet = []
production = []
no-entrypoint = []
sbf-entrypoint = ["no-entrypoint", "no-idl"]
cpi = ["no-entrypoint"]
no-idl = []
no-log-ix-name = []
anchor-debug = []
idl-build = ["anchor-lang/idl-build"]
wrong-vk = []
[dependencies]
anchor-lang = "=0.31.1"
anchor-spl = { version = "=0.31.1", default-features = false, features = ["token", "associated_token"] }
solana-program = "=2.2.1"
groth16-solana = "=0.2.0"
zkapi-layout2 = { path = "../../crates/zkapi-layout2" }
[build-dependencies]
bs58 = "=0.5.1"
ark-ed-on-bn254 = { version = "=0.5.0", default-features = false }
ark-ec = { version = "=0.5.0", default-features = false }
ark-ff = { version = "=0.5.0", default-features = false }
[dev-dependencies]
ark-ed-on-bn254 = { version = "=0.5.0", default-features = false }
ark-ec = { version = "=0.5.0", default-features = false }
ark-ff = { version = "=0.5.0", default-features = false }
[profile.release]
lto = "fat"
codegen-units = 1
